### ISSUE TITLE
Swarm with different trajectory

### ISSUE THREAD

**Issue by shiva02** [voodootikigod/node-rolling-spider#46]
Hello everyone.
Is it possible to make a different trajectory for each drones of swarm ?
May be using an index element of the swarm like this : 
   swarm.membership[0].takeOff()
If you have an idea?

**Comment by voodootikigod** [comment]
Use `swarm.at('RS_W123456').forward()`

**Comment by voodootikigod** [comment]
https://github.com/voodootikigod/node-rolling-spider#swarmatid-callback

**Comment by shiva02** [comment]
How thanks...
I am beginner and I had not seen the new doc...
Thanks a lot

**Comment by voodootikigod** [comment]
No worries, just got it up actually because you filed the ticket so thank
you for the nudge ;) cheers and best of flying

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.
